---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
  namespace: aap25
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app.kubernetes.io/managed-by: aap-operator
    app.kubernetes.io/name: aap
    app.kubernetes.io/operator-version: '2.5'
    app.kubernetes.io/part-of: aap
spec:
  idle_aap: true
  database:
    database_secret: external-postgres-configuration-gateway
    idle_disabled: true
    postgres_data_volume_init: false
  controller:
    postgres_configuration_secret: external-postgres-configuration-controller
    garbage_collect_secrets: false
    disabled: false
    name: ac
    ee_extra_env: |
      - name: RECEPTOR_KUBE_SUPPORT_RECONNECT
        value: enabled
    extra_settings:
      - setting: AWX_RUNNER_KEEPALIVE_SECONDS
        value: 240
  eda:
    disabled: true
    name: eda
    database:
      database_secret: external-postgres-configuration-eda
    event_stream:
      database_secret: external-postgres-configuration-eda-event-stream
  hub:
    disabled: true
    file_storage_size: 50Gi
    name: hub
    storage_type: file
    pulp_settings:
      cache_enabled: false
    postgres_configuration_secret: external-postgres-configuration-hub
  lightspeed:
    disabled: true
  extra_settings:
    - setting: REDIRECT_IS_HTTPS
      value: '"True"'
  feature_flags:
    FEATURE_POLICY_AS_CODE_ENABLED: true
  image_pull_policy: IfNotPresent
  no_log: true
  redis_mode: standalone
  route_tls_termination_mechanism: Edge
...
